### ISSUE TITLE
No stale Helm charts found.

### ISSUE THREAD

**Issue by karl18** [FairwindsOps/helm-release-pruner#15]
Hi, I love this helm chart, but unfortunately looks like it's not working on my cluster.
I tried to configure the prune profiles as follows:

`pruneProfiles: `
`- olderThan: "4 days ago" `
`  helmReleaseFilter: '\W*((?i)feature(?-i))\W*'`
`  namespaceFilter: ".*"`
 ` maxReleasesToKeep: 0`

I'm trying to find any helm release with the name "-feature" in all namespaces and prune those who are 4 days ago.
After several tries, I tried almost all possibilities with release & ns filters, then reached the point that the script is not able to find any kind of charts with any keywords or namespaces.

I believe this maybe related to permissions or service accounts, although I see admin role is already created!
Here's my helm-chart followed by my script result

Deployed Helm chart:
fullnameOverride: stg-helm-release-pruner
image:
  pullPolicy: Always
  repository: quay.io/fairwinds/helm-release-pruner
  tag: v3.2.1
job:
  backoffLimit: 3
  debug: true
  dryRun: true
  listSecretsRole:
    create: true
    name: helm-release-pruner-list-secrets
  resources:
    limits:
      cpu: 25m
      memory: 32Mi
    requests:
      cpu: 25m
      memory: 32M
  restartPolicy: Never
  schedule: '*/60 * * * *'
  serviceAccount:
    create: true
    name: helm-release-pruner
nameOverride: ""
pruneProfiles:
- helmReleaseFilter: \W*((?i)feature(?-i))\W*
  maxReleasesToKeep: 0
  namespaceFilter: .*
  olderThan: 4 days ago
rbac_manager:
  enabled: false
  namespaceLabel: ""
resources:
  limits:
    cpu: 25m
    memory: 32Mi
  requests:
    cpu: 25m
    memory: 32M
`

script result:
`+ max_releases_to_keep=
+ older_than_filter=
+ release_filter=
+ namespace_filter=
+ dry_run=
+ '[' '--older-than=14 days ago' '!=' '' ']'
++ echo --older-than=14 days ago
++ awk -F= '{print $1}'
+ PARAM=--older-than
++ echo --older-than=14 days ago
++ awk -F= '{print $2}'
+ VALUE='14 days ago'
+ case $PARAM in
+ older_than_filter='14 days ago'
+ shift
+ '[' '--helm-release-filter=^webshop-' '!=' '' ']'
++ echo '--helm-release-filter=^webshop-'
++ awk -F= '{print $1}'
+ PARAM=--helm-release-filter
++ echo '--helm-release-filter=^webshop-'
++ awk -F= '{print $2}'
+ VALUE='^webshop-'
+ case $PARAM in
+ release_filter='^webshop-'
`

Any suggessions? I appreciate your help!

Best,Kareem

**Comment by sudermanjr** [comment]
I'm a bit confused by the script output here. It seems to show `^webshop-` as the release filter, not the regex you shared. I haven't actually used this tool in a bit though, so I could just be misunderstanding something.

**Comment by rbren** [comment]
The output of `helm ls -A` will be helpful here.

We're using bash regexen, so I'm not sure the `(?i)` (lookahead?) is supported. You can see if this matches:
```bash
      if [[ "my-namesace" =~ "my-filter-regex" ]]; then
          echo "regex matches, will get pruned"
      fi
```

**Comment by karl18** [comment]
Hi @sudermanjr @rbren thx for your reply, sorry for delaying mine a bit!
I fixed the regex used to match bash regex, but even running the script locally doesn't solve the issue.
I would be happy to show you the changes I did to the chart as well as the output of the script, so you might be able to see where is the problem exactly! 

Basically, what I'm trying to achieve is to find a chart contains the word `feature` for any or all namespaces I have-
Here's the chart details I want to match & the output of `helm ls -A` in a txt file (the command runs at the end of the script but `helm ls -a --all-namespaces --date --reverse` with reversed dates{doesn't even matter
[helm_all_releases.txt](https://github.com/FairwindsOps/helm-release-pruner/files/9239881/helm_all_releases.txt)
[helm_all_releases_date_reverse.txt](https://github.com/FairwindsOps/helm-release-pruner/files/9239882/helm_all_releases_date_reverse.txt)
}):

`voucher-api-kareem-test-feature     	voucher-api                         	1       	2022-07-21 14:33:11.231842143 +0000 UTC	deployed	voucher-api-kareem-test-feature-staging-0.1.5-kareem-test.13                                	            `

`fullnameOverride: dev-helm-release-pruner

job:
  schedule: "0 5 * * 1"
  dryRun: false
  debug: true

resources:
    limits:
      cpu: 25m
      memory: 32Mi
    requests:
      cpu: 25m
      memory: 32M

pruneProfiles:
- olderThan: "7 days ago"
  helmReleaseFilter: '*feature*'
  namespaceFilter: "*"
  maxReleasesToKeep: 0`
  
  

<details>
<summary>script output</summary>

+ max_releases_to_keep=
+ older_than_filter=
+ release_filter=
+ namespace_filter=
+ dry_run=
+ '[' '--older-than=4 days ago' '!=' '' ']'
++ echo --older-than=4 days ago
++ awk -F= '{print $1}'
+ PARAM=--older-than
++ echo --older-than=4 days ago
++ awk -F= '{print $2}'
+ VALUE='4 days ago'
+ case $PARAM in
+ older_than_filter='4 days ago'
+ shift
+ '[' '--helm-release-filter=*feature*' '!=' '' ']'
++ awk -F= '{print $1}'
++ echo '--helm-release-filter=*feature*'
+ PARAM=--helm-release-filter
++ echo '--helm-release-filter=*feature*'
++ awk -F= '{print $2}'
+ VALUE='*feature*'
+ case $PARAM in
+ release_filter='*feature*'
+ shift
+ '[' '--namespace-filter=*' '!=' '' ']'
++ ++ echo awk -F= '--namespace-filter=*''{print $1}'

+ PARAM=--namespace-filter
++ ++ awk echo -F= '--namespace-filter=*''{print $2}'

+ VALUE='*'
+ case $PARAM in
+ namespace_filter='*'
+ shift
+ '[' --dry-run '!=' '' ']'
++ echo --dry-run
++ awk -F= '{print $1}'
+ PARAM=--dry-run
++ echo --dry-run
++ awk -F= '{print $2}'
+ VALUE=
+ case $PARAM in
+ dry_run=TRUE
+ shift
+ '[' '' '!=' '' ']'
+ [[ -z 4 days ago ]]
++ date '--date=4 days ago' +%s
+ older_than_filter_s=1659074561
+ '[' -n TRUE ']'
+ echo 'Dry run mode. Nothing will be deleted.'
Dry run mode. Nothing will be deleted.
+ counter=0
+ counter_keep=0
+ counter_delete=0
+ read release_line
++ helm ls -a --all-namespaces --date --reverse
/usr/local/bin/prune-releases.sh: line 143:    32 Killed                  helm ls -a --all-namespaces --date --reverse
No stale Helm charts found.
+ '[' 0 -gt 0 ']'
+ echo 'No stale Helm charts found.'

</details>

**Comment by karl18** [comment]
**small update:** Well, I see some bug or maybe an error in the most bottom output of the script!
`/usr/local/bin/prune-releases.sh: line 143:    32 Killed                  helm ls -a --all-namespaces --date --reverse`
`No stale Helm charts found.`
it seems to be that helm ls -A --date --reverse couldn't run for some reason!

**Now found my issue!:** I believe according to some online search, I found that the cronJob was failing due to OOM error because there was not enough memory to run the script. This is why I see 32 Killed in the output of the script!

**Comment by karl18** [comment]
Just before closing this issue, I still cannot match the name using this filter:
`helmReleaseFilter: "*feature*"`
`namespaceFilter: "*"`

script output:
++ awk '-F\t' '{ print $2 }'
++ tr -d ' '
+ release_namespace=voucher-api
+ [[ -n *feature* ]]
+ [[ voucher-api-kareem-test-feature =~ *feature* ]]
+ continue
+ read release_line
+ counter=27
+ release_date=
+ release_date_s=0
+ release_name=
+ release_namespace=
+ [[ 27 -eq 1 ]]

**Comment by karl18** [comment]
Okay, I solved this issue by using: 
`helmReleaseFilter: '.*feature$'`
 `namespaceFilter: ".*"`

The only drawback, I find in this script, Is that it doesn't support deleting several releases under the same Namespace.
Could I open another Feature request for this? It should be a small change, I believe

**Comment by rbren** [comment]
Oh interesting - I think you're right! Yes, feel free to open an issue for multiple releases in the same namespace.

Glad you figured it out, thanks for the update!
